recipes-bsp: most-tools: most_play.sh: Fix "wrong format" error
This fixes the following playback error:
  ERROR: from element /GstPipeline:pipeline0/GstAlsaSink:alsasink0:
         The stream is in the wrong format.

Looks like "avdec_mp3" produces output format which has the
following properties not currently supported by alsalink:
 - layout=(string)non-interleaved;
 - channel-mask=(bitmask)0x0000000000000003.

Insert "audioconvert" right after "avdec_mp3" in the gstreamer
pipeline in the most_play.sh script. This converts "avdec_mp3"
output to the appropriate alsasink format.

Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>