recipes-devtools: yaml-cpp 0.5.3: Remove "-DLIB_SUFFIX=64" from EXTRA_OECMAKE
Install libraries to /usr/lib instead of /usr/lib64 to fix
the following do_package failure:

  ERROR: yaml-cpp-0.5.3-r0 do_package: QA Issue: yaml-cpp:
  Files/directories were installed but not shipped in any package:
    /usr/lib64/libyaml-cpp.so.0.5
    /usr/lib64/libyaml-cpp.so
    /usr/lib64/libyaml-cpp.so.0.5.3
    /usr/lib64/pkgconfig
    /usr/lib64/pkgconfig/yaml-cpp.pc

Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>