recipes-kernel: linux-renesas: soc_camera: Fix R-Car VIN and CSI2 build issue
This adds "select V4L2_FWNODE" to VIDEO_RCAR_VIN_LEGACY and
VIDEO_RCAR_CSI2_LEGACY configuration options since both VIN
and CSI2 legacy drivers use V4L2_FWNODE API.
This helps to avoid the following build issue when other
drivers using V4L2_FWNODE are disabled:
  undefined reference to `v4l2_fwnode_endpoint_parse'

Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>