recipes-core: images: Fix core-image-minimal build for non-v3x SoCs
This adds v3x dependency for v3x package group which fixes the following
build error for non v3x SoCs:
  ERROR: Nothing RPROVIDES 'libiccom' (but packagegroup-v3x.bb
         RDEPENDS on or otherwise requires it)

Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>