cr7-loader: use default EXTRA_OEMAKE to provide additional flags instead of using custom variable.
This patch fixed build error:

ERROR: cr7-loader-v1.0+renesas+git-r0 do_configure: oe_runmake failed
Log data follows:
| DEBUG: Executing shell function do_configure
| NOTE: make clean
| Makefile:77: *** "Error: Unknown LSI. Please use LSI=<LSI name> to specify the LSI". Stop.
| ERROR: oe_runmake failed